export const DEPARTMENTS = [
  'Hospitals',
  'Clinics',
  'Restaurants',
  'Retail',
  'Schools',
  'Colleges',
  'Real Estate',
  'Automobiles',
  'Hotels',
  'Manufacturing',
  'Professional Services',
  'Salons & Spa',
  'Gyms & Fitness',
  'Electronics',
  'Construction',
  'Agriculture',
  'Other',
];
